#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#MISE description="Run formatting check and vet"
set -euo pipefail

UNFORMATTED=$(gofmt -l .)
if [ -n "$UNFORMATTED" ]; then
    echo "Files not formatted:"
    echo "$UNFORMATTED"
    exit 1
fi
go vet ./...
