#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#MISE description="Run all Rust tests"
#MISE sources=["crates/**/*.rs", "src-tauri/**/*.rs", "Cargo.toml", "Cargo.lock"]
set -euo pipefail

cargo test --workspace
